"""empty message

Revision ID: 0f7a04d298ea
Revises: 
Create Date: 2019-08-17 00:32:31.374055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7a04d298ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article3',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tittle', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=100), nullable=False),
    sa.Column('tags1', sa.String(length=100), nullable=False),
    sa.Column('tags2', sa.String(length=100), nullable=False),
    sa.Column('tags3', sa.String(length=100), nullable=False),
    sa.Column('tags4', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('article3')
    # ### end Alembic commands ###
